### PR TITLE
Add example for pointerMovementScrolls

### PR DESCRIPTION
**Pull request by RByers**
For #22

### CODE REVIEW

**Comment by RByers** [comment]
@dtapuska WDYT?  Note that I intentionally avoided complicating this by adding feature detection or trying to handle additional types of input events (TouchEvents).

Also @patrickhlauke, @scottgonzalez @teddink any feedback on [this example](https://rawgit.com/WICG/InputDeviceCapabilities/ece3d2cac16a98546f1af86f8677392fac639646/index.html#example_2) or the [API spec](https://wicg.github.io/InputDeviceCapabilities/#dom-inputdevicecapabilities-pointermovementscrolls)?.

**Comment by scottgonzalez** [comment]
Looks good. I don't think the extra complexity would be necessary anyway.

**Comment by dtapuska** [comment]
lgtm; thanks for writing that

**Comment by RByers** [comment]
Thanks guys.

**Comment by patrickhlauke** [comment]
a late +1 from me

**Pull request merged**
