### PR TITLE
Add explicit [Exposed] + default dictionary value

### PR DESCRIPTION
**Pull request by saschanaz**
Required after heycam/webidl#423 and heycam/webidl#750. (Found from web-platform-tests/wpt#18382)

### CODE REVIEW

**Comment by saschanaz** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by yoavweiss** [comment]
@saschanaz - Thanks for updating the IDL! :) while this is probably non-substantive, it'd still be better if you could join the WICG and link your GH account to your W3C one

**Comment by saschanaz** [comment]
Marked as  substantive for IPR from ash-nazg.

**Review by yoavweiss — APPROVED** [review]
LGTM

**Pull request merged**
